### ISSUE TITLE
Version on pypi missing requirements.txt

### ISSUE THREAD

**Issue by pigriffin** [alvinwan/tex2py#2]
Trying to install using pip I get the following errors. It seems that the requirements.txt is missing from the archive on pypi:

$ pip install tex2py-0.0.1.tar.gz 
...
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-qx8JUe-build/setup.py", line 7, in <module>
        with open('requirements.txt') as f:
    IOError: [Errno 2] No such file or directory: 'requirements.txt'

Downloading the archive manually and looking at it confirms this:
        ----------------------------------------
$ tar tzvf tex2py-0.0.1.tar.gz 
drwxr-xr-x alvinwan/staff    0 2016-05-20 14:51 tex2py-0.0.1/
-rw-r--r-- alvinwan/staff  531 2016-05-20 14:51 tex2py-0.0.1/PKG-INFO
-rw-r--r-- alvinwan/staff   59 2016-05-20 14:51 tex2py-0.0.1/setup.cfg
-rw-r--r-- alvinwan/staff 1473 2016-05-20 14:20 tex2py-0.0.1/setup.py
drwxr-xr-x alvinwan/staff    0 2016-05-20 14:51 tex2py-0.0.1/tex2py/
-rw-r--r-- alvinwan/staff  271 2016-05-20 03:57 tex2py-0.0.1/tex2py/__init__.py
-rw-r--r-- alvinwan/staff 9467 2016-05-20 14:16 tex2py-0.0.1/tex2py/tex2py.py
drwxr-xr-x alvinwan/staff    0 2016-05-20 14:51 tex2py-0.0.1/tex2py.egg-info/
-rw-r--r-- alvinwan/staff    1 2016-05-20 14:51 tex2py-0.0.1/tex2py.egg-info/dependency_links.txt
-rw-r--r-- alvinwan/staff  531 2016-05-20 14:51 tex2py-0.0.1/tex2py.egg-info/PKG-INFO
-rw-r--r-- alvinwan/staff   50 2016-05-20 14:51 tex2py-0.0.1/tex2py.egg-info/requires.txt
-rw-r--r-- alvinwan/staff  193 2016-05-20 14:51 tex2py-0.0.1/tex2py.egg-info/SOURCES.txt
-rw-r--r-- alvinwan/staff    7 2016-05-20 14:51 tex2py-0.0.1/tex2py.egg-info/top_level.txt

**Comment by scholer** [comment]
I'm having the same issue. Seems easy to fix, either include the requirements file or wrap the ```open('requirements.txt')``` statement in a try...except clause and fall back to hard-coded values (especially since there is only a single required dependency!)

**Comment by pigriffin** [comment]
I'm new to python. More used to 'make dist'. So I don't know how to fix this as the packaging process seems to be manual and outside the git repo? When I run 'python setup.py sdist' in the package dir the generated tar.gz file has requirements.txt included. So without a Makefile or equivalent there seems to be no way to fix this with a pull request?

**Comment by scholer** [comment]
You need to specify which files are to be included when packaging the distribution file. 
There are at least three ways of specifying the files to include in the distribution:

1. In `setup.py`, using arguments to `setup(...)`, e.g. `packages` (for python files), `package_data` (installs files inside your package directory), and `data_files` (installs files outside the package directory; advanced). The `setup()` call is used to *install* the distribution files on the user's system, so it makes sense to automatically include these files when packaging up the distribution. 
2. In the MANIFEST file. If a manifest file is specified, it must list every single file that you wish to include in the distribution. If a file is not listed, it is not included. Outdated MANIFEST files are an obvious source for packaging failure; *avoid using a manual MANIFEST file unless you are an expert and know that this is in fact the only optimal way to package your distribution*. 
3. Instead of manually listing each individual file in the MANIFEST file, developers should generally use a **manifest template** (`MANIFEST.in`) to provide instructions about the files to include or exclude. The instructions in the manifest template are applied *after* gathering the default set of files. So you only need to add *additional* files not already covered by the default set of files.

Currently, `requirements.txt` is not specified in `setup()`, and we do not have a MANIFEST or manifest template, so `requirements.txt` is not included when the `sdist` command is determining which files to include in the distribution package.

In our case, we want to include the `requirements.txt` file in our distribution package, but we do not need to actually install the `requirements.txt` file onto the user's system. It just needs to be available inside the packaged distribution, so it can be read when `setup.py` tries to `open` it. Thus, we should include the requirements file by adding it to the manifest; and we add it to the manifest by creating a manifest template and adding a line in the manifest template instructing the `sdist` packaging command to include `requirements.txt` when generating the manifest.

Refs:
* https://docs.python.org/3/distutils/sourcedist.html#manifest

**Comment by scholer** [comment]
OBS: In order to upload an updated distribution package to PYPI (using `python setup.py sdist upload -r pypi`), you have to either bump the version number, or delete the old distribution file (`tex2py-0.0.1.tar.gz`) from the distribution files page.

* https://pypi.python.org/pypi?:action=files&name=tex2py&version=0.0.1

**Comment by johnyf** [comment]
Just two quick comments:

- forgetting to include files in `MANIFEST.in` is a common error. Whenever making a release, it is good practice to include in the checklist to run [`check-manifest`](https://github.com/mgedmin/check-manifest). Also, two other checks are worth the effort:
  1. install and test via `pip`, not in editable mode, so detect necessary files that are missing from the distribution tarball. [Example `.travis.yml`](https://github.com/johnyf/omega/blob/a808dc1a5b02d451ddce6e33640562f00a2a4771/.travis.yml#L15).
  2. use `testpypi.python.org`. You could use a local version identifier (`dev...`) to avoid testing upload errors from forcing you to bump version number.

- I believe that it is imposible to upload a different distribution file (mentioned as an alternative [above](https://github.com/alvinwan/tex2py/issues/2#issuecomment-282434222)). Please see: https://github.com/pypa/pypi-legacy/issues/206, and also: https://github.com/pypa/packaging-problems/issues/74.
